### ISSUE TITLE
Add screenshot of a panic message and backtrace in a browser's developer console

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/console_error_panic_hook#1]
So users get an idea what to expect.

**Comment by migerh** [comment]
Something like this? 
![panic_hook](https://user-images.githubusercontent.com/368715/42841190-93546404-8a09-11e8-9e53-d41b3a30e9cb.png)

**Comment by fitzgen** [comment]
@migerh exactly like that!

Also, a "before" version to go with the nicer "after" version would be nice to drive it home :)

**Comment by migerh** [comment]
Sure:
![without_panic_hook](https://user-images.githubusercontent.com/368715/42905943-d7cdc730-8ad9-11e8-844f-46fe37d9ed7c.png)
![with_panic_hook](https://user-images.githubusercontent.com/368715/42905944-d7f549a4-8ad9-11e8-80be-cac03eee8c36.png)

Also, I noticed that in Chrome I get the (almost, minus the hook of course) same stacktrace with and without the panic hook - BUT with the panic hook I get a nice message that helps with the debugging. Without the hook only `RuntimeError: unreachable` is reported.

**Comment by fitzgen** [comment]
@migerh so would you like to send a PR adding these images to the README? That's the end goal of this issue -- sorry if that wasn't clear.

Re: chrome vs firefox stacks, I think it is a bug that firefox does not have a stack attached to the `RuntimeError`.

**Comment by migerh** [comment]
The only thing unclear until your comment was where to add the screenshots - README or docs? :wink:

I added them to the README now. If you want them in the docs as well we could use the direct link to the images in the merge commit once the PR is merged and add them there as well.
