### ISSUE TITLE
Add example error message and backtrace from node

### ISSUE THREAD

**Issue by fitzgen** [rustwasm/console_error_panic_hook#2]
I think this can be text rather than a screenshot like in #1 since node just has a REPL and no GUI.

**Comment by kylejlin** [comment]
I can take care of this. Where do you want me to add the error messages? In the README?

**Comment by kylejlin** [comment]
Since I wasn't sure where you wanted them, I put them in `.txt` files for now. #9

**Comment by fitzgen** [comment]
Fixed in #9
