### ISSUE TITLE
Doesn't work in Safari

### ISSUE THREAD

**Issue by kzvi** [rustwasm/console_error_panic_hook#7]
What I see in Firefox:

![](https://imgur.com/kCaj6QW.png)

What I see in Safari:

![](https://imgur.com/DwvWTCf.png)

Edit:

wasm-bindgen generates this code:

```
const __wbg_error_29632ca09755cc79_target = console.error;

let cachedDecoder = new TextDecoder('utf-8');

// ...

export function __wbg_error_29632ca09755cc79(arg0, arg1) {
    let varg0 = getStringFromWasm(arg0, arg1);
    __wbg_error_29632ca09755cc79_target(varg0);
}
```

If this line:

```
__wbg_error_29632ca09755cc79_target(varg0);
```

is manually changed to this:

```
__wbg_error_29632ca09755cc79_target(varg0 + " ");
```

then it works. It seems that the string literal has to have a space in it, an empty string literal doesn't work.

**Comment by fitzgen** [comment]
If you add a breakpoing before the `__wbg_error_29632ca09755cc79_target` call, is `varg0` the exepcted error message string?

This is super funky behavior...

Unfortunately, I don't have an OSX machine on hand at the moment.

**Comment by kzvi** [comment]
If I inspect `varg0` using the console:

![](https://www.dropbox.com/s/rhgfyowh1mnra8t/Screen%20Shot%202018-09-18%20at%201.54.48%20PM.png?raw=1)

**Comment by fitzgen** [comment]
It looks like this is a bug in Safari's developer console.

We can work around it by appending a space to the error message, I suppose...

**Comment by fitzgen** [comment]
Filed an upstream bug report to webkit's devtools: https://bugs.webkit.org/show_bug.cgi?id=189750

**Comment by fitzgen** [comment]
@kzvi, could you comment in the webkit bug with which safari version you are using? Alternatively, if you don't have an account for bugs.webkit.org and don't want one, you can leave a comment here and I can copy it over to the webkit bug. Thanks!

**Comment by thavlik** [comment]
Still not working in Safari 12.0.3 (14606.4.5)
